main: net.farugames.api.spigot.SpigotFaruAPI
name: FaruGamesAPI
version: ${project.version}
authors: [3DX900, ChocoIG, SweetKebab_]
depends: [FaruGamesData]
commands:
    gamemode:
      aliases: [gm]
    list:
    maintenance:
    message:
      aliases: [msg,m,whisper,w,tell,t,mp]
    punish:
    rank:
    reply:
      aliases: [rep,r,response,respond,resp]
    servermanager:
      aliases: [sm]
    serverteleport:
      aliases: [servertp,stp,steleport]
    teleport:
      aliases: [tp]