main: net.farugames.api.spigot.Main
name: FaruGamesAPI
version: 0.5.2
authors: [3DX900, ChocoIG]
depends: [FaruGamesData]
commands:
    gamemode:
      aliases: [gm]
    teleport:
      aliases: [tp]